version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=db_solita
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=postgres
    ports:
      - "5243:5432"
